### GET request to example server
POST http://localhost:4004/api/patients
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name" : "kafka Service Testing",
    "email" : "KafkaService@gmail.com",
    "address" : "123 Main Street",
    "dateOfBirth" : "2003-07-31",
    "registeredDate" : "2003-07-31"
}

###